select_game = "Select a game mode..."
wait_for_player = "Click to continue..."
game_lost = "You lost!"
game_won = "Congratulations, you won."

[menu]
title_game = "Game"
start_easy_game = "Start easy game"
start_med_game = "Start medium game"
start_hard_game = "Start hard game"
quit_game = "Quit Minesweeper"
title_help = "Help"
about = "About Minesweeper"
